version: '3.8'

volumes:
  openbound_fetch_server_data: {}

services:
    %container_name%:
        build:
            context: ../
            dockerfile: Docker/Dockerfile.OpenBoundFetchServer
            target: %container_name%
            cache_from:
                - %container_name%:latest
        image: %container_name%
        container_name: %container_name%
        restart: always
        ports:
            - %local_port%:%container_port%
        healthcheck:
            test: bash -c "</dev/tcp/openbound-fetch-server/%container_port% && exit 0 || exit 1"
            start_period: 30s
            interval: 30s
            timeout: 10s
            retries: 3
        logging:
            driver: 'json-file'
            options:
                max-size: '1m'
                max-file: '5'